on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
      
  workflow_dispatch:
  
name: Main Workflow
jobs:
  sonarcloud:
    name: dotnet-sonarcloud-analysis
    uses: spoland/dotnet-sonarcloud-analysis@v1.0
    with:
        project-key: WillMacaulay_myApp3
        sonar-host-url: https://sonarcloud.io
        sonar-organization: willmacaulay
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   
